spring:
  datasource:
    url: jdbc:mysql://mysql:3306/${MYSQL_DB}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: redis
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update   # create / update / validate / none 중 선택 가능
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

tour-api:
  service-key: ${TOUR_API_SERVICE_KEY}

JWT_SECRET: ${JWT_SECRET}
JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}